theme : "modern"
theme_advanced_toolbar_location : "top"
theme_advanced_toolbar_align : "center"
theme_advanced_statusbar_location : "none"
theme_advanced_buttons1 : "bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,|,bullist,numlist,|,link,unlink,|,sub,sup,|,fontsizeselect,forecolor"
theme_advanced_buttons2 : ""
theme_advanced_buttons3 : ""
valid_elements : "@[id|class],a[name|href|target|title],strong/b,em/i,strike,u,#p,-ol[type|compact],-ul[type|compact],-li,br,img[longdesc|usemap|src|border|alt=|title|hspace|vspace|width|height|align],-sub,-sup,-blockquote,-table[border=0|cellspacing|cellpadding|width|height|align|summary|bgcolor|background|bordercolor],-tr[rowspan|width|height|align|valign|bgcolor|background|bordercolor],tbody,thead,tfoot,#td[colspan|rowspan|width|height|align|valign|bgcolor|background|bordercolor|scope],#th[colspan|rowspan|width|height|align|valign|scope],caption,-div,-span,-code,-pre,address,-h1,-h2,-h3,-h4,-h5,-h6,hr[size|noshade],-font[size],dd,dl,dt,cite,abbr,acronym,button,col[align|char|charoff|span|valign|width],colgroup[align|char|charoff|span|valign|width],dfn,label[for],legend,small,tt,var,big"
content_css : "/tinymce.css"
plugins : "autoresize"
height: 160
autoresize_min_height: 160